### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by Registradorold** [zRitsu/disnake-LL-music-bot#14]
@zRitsu  A alguma forma de colocar um prefixo diferente para cada token?

**Comment by zRitsu** [comment]
nessa parte do .env-example tem explicando como usar tokens adicionais com prefixo diferente: https://github.com/zRitsu/disnake-LL-music-bot/blob/main/.env-example#L2

**Comment by zRitsu** [comment]
> 

só colocar: "token prefix"
ex: ```py
TOKEN_BOT_TEUBOT="AbcdEfghjklm.nopqrstuv --"
```
