### ISSUE TITLE
tá dando um erro pra mim, não sei se é pra alguns mas pra mim deu esse erro

### ISSUE THREAD

**Issue by alexkeiper** [zRitsu/disnake-LL-music-bot#16]
/users/@me"))
W  File "/usr/local/lib/python3.10/site-packages/disnake/http.py", line 442, in request
(    raise HTTPException(response, data)
Rdisnake.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
N  File "/home/user_903283721770237974/utils/client.py", line 32, in start_bot
    await bot.start(bot.token)
W  File "/usr/local/lib/python3.10/site-packages/disnake/client.py", line 886, in start
    await self.login(token)
W  File "/usr/local/lib/python3.10/site-packages/disnake/client.py", line 741, in login
7    data = await self.http.static_login(token.strip())
\  File "/usr/local/lib/python3.10/site-packages/disnake/http.py", line 493, in static_login
C    raise LoginFailure("Improper token has been passed.") from exc
=disnake.errors.LoginFailure: Improper token has been passed.
Unclosed client session
Hclient_session: <aiohttp.client.ClientSession object at 0x7fc74637ef80>
Unclosed client session
Hclient_session: <aiohttp.client.ClientSession object at 0x7fc74637e3b0>
Unclosed client session
Hclient_session: <aiohttp.client.ClientSession object at 0x7fc74637e1d0>
&Task was destroyed but it is pending!
�task: <Task pending name='Task-2' coro=<Misc.presences() running at /home/user_903283721770237974/modules/misc.py:68> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Unclosed client session
Hclient_session: <aiohttp.client.ClientSession object at 0x7fc745fbc1c0>
&Task was destroyed but it is pending!
�task: <Task pending name='Task-5' coro=<BotPool.connect_spotify() running at /home/user_903283721770237974/utils/client.py:70> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Unclosed connector
hconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fc745f4f6a0>, 3809770.800353849)]']
Econnector: <aiohttp.connector.TCPConnector object at 0x7fc745f0e860>
&Task was destroyed but it is pending!
�task: <Task pending name='Task-1' coro=<CommonBotBase._fill_owners() running at /usr/local/lib/python3.10/site-packages/disnake/ext/commands/common_bot_base.py:116> wait_for=<Future pending cb=[Task.task_wakeup()]>>
&Task was destroyed but it is pending!
task: <Task pending name='disnake: app_command_preparation' coro=<InteractionBotBase._prepare_application_commands() running at /usr/local/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py:785> wait_for=<Future pending cb=[Task.task_wakeup()]>>

**Comment by zRitsu** [comment]
ta executando o bot onde?

**Comment by reopopiewr** [comment]
deu o mesmo para mim

**Comment by zRitsu** [comment]
o token do bot ta errado ou foi resetado/regenerado.
