### ISSUE TITLE
bug: Bot bugado em canais de fórum

### ISSUE THREAD

**Issue by Kuriel23** [zRitsu/disnake-LL-music-bot#22]
Ao falar em algum canal de fórum, o bot apaga a mensagem e envia a mensagem "Você deve entrar em um canal de voz para pedir uma música."

**Comment by zRitsu** [comment]
uma dúvida, o post que o bot faz isso foi criado por outro bot ou por membro comum?

**Comment by Kuriel23** [comment]
outro bot

**Comment by Kuriel23** [comment]
utilizando o bot muse heart também acontece o mesmo, outro detalhe que vi no bug é que isso só acontece enquanto o player toca.

**Comment by zRitsu** [comment]
se possivel tem como gravar um video testando isso?

**Comment by zRitsu** [comment]
foi adicionado um fix temporário, mas o bot ainda pode reagir a postagens de algum bot rodando na mesma instancia (mesmo não sendo do controller), vou corrigir isso até amanhã.

https://github.com/zRitsu/disnake-LL-music-bot/commit/d1f576f9504691b3bc2d4739fa2c22f7aaca55a4

**Comment by Kuriel23** [comment]
Beleza!

**Comment by zRitsu** [comment]
corrigido já, muito obrigado por reportar isso
