### ISSUE TITLE
Falta de Módulo Tinymongo

### ISSUE THREAD

**Issue by Dio141** [zRitsu/disnake-LL-music-bot#23]
Atualizei o bot hoje mais cedo, e ao tentar usar ele, não funciona. vendo no cmd, acusa falta desse modulo.
iniciando bot (verifique se ele está online)...

(venv) E:\Bots\disnake-LL-music-bot>python main.py  2>.logs\run.log

(venv) E:\Bots\disnake-LL-music-bot>type .logs\run.log
Traceback (most recent call last):
  File "E:\Bots\disnake-LL-music-bot\main.py", line 1, in <module>
    from utils.client import BotPool
  File "E:\Bots\disnake-LL-music-bot\utils\client.py", line 16, in <module>
    from utils.music.checks import check_pool_bots
  File "E:\Bots\disnake-LL-music-bot\utils\music\checks.py", line 9, in <module>
    from utils.music.models import LavalinkPlayer
  File "E:\Bots\disnake-LL-music-bot\utils\music\models.py", line 11, in <module>
    from utils.db import DBModel
  File "E:\Bots\disnake-LL-music-bot\utils\db.py", line 12, in <module>
    from tinymongo import TinyMongoClient
ModuleNotFoundError: No module named 'tinymongo'

Waiting for 24 seconds, press a key to continue ...

**Comment by zRitsu** [comment]
usa o setup.sh antes ou o update.sh

**Comment by Dio141** [comment]
no caso sempre atualizo com o update.sh, mas vou tentar aqui com o setup.

**Comment by zRitsu** [comment]
> no caso sempre atualizo com o update.sh, mas vou tentar aqui com o setup. EDIT: usar o setup funcionou. Update.sh não tinha baixado as novas dependências, pelo que entendi. Obrigado pela ajuda!

blz, mas mesmo assim vou rever o update.sh, pois era pra ele ter atualizado/instalado a dependência nesse processo, vlw pelo report
