### ISSUE TITLE
Erro Connection Failure

### ISSUE THREAD

**Issue by Saaamx** [zRitsu/disnake-LL-music-bot#31]
WEBSOCKET | Connection Failure:: Cannot connect to host node3.garvv.me:1102 ssl:default [getaddrinfo failed]
ClientConnectorError(ConnectionKey(host='node3.garvv.me', port=1102, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11001, 'getaddrinfo failed'))

do nada começou a dar para mim esse erro

**Comment by zRitsu** [comment]
esse erro é normal em servidores de música (lavalink) públicos, quando da esse erro o bot não usa o servidor até a conexão ser restabelecida.

**Comment by zRitsu** [comment]
pra ver todos os servidores disponiveis/com falha usa o comando /nodeinfo

**Comment by zRitsu** [comment]
Se tiver com algum problema na reprodução das músicas em si tente mandar print com erros etc.
