### ISSUE TITLE
RuntimeError on terminal

### ISSUE THREAD

**Issue by cmk-Destro** [zRitsu/disnake-LL-music-bot#8]
i get RuntimeError: Can't restart token refresh task when previous refresh failed
when i run run.sh, i dont know why i didnt change any code only added the spotfiy token and discord bot token
![image](https://user-images.githubusercontent.com/85604461/169666369-bf435c06-648d-4698-86c7-0a9b7597f991.png)

**Comment by zRitsu** [comment]
TYVM ❤️
